/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddFollowDto
 */
export interface AddFollowDto {
    /**
     * 
     * @type {boolean}
     * @memberof AddFollowDto
     */
    disabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AddFollowDto
     */
    followName: string;
    /**
     * 
     * @type {string}
     * @memberof AddFollowDto
     */
    sourceDevice: string;
    /**
     * 
     * @type {number}
     * @memberof AddFollowDto
     */
    sourcePin: number;
    /**
     * 
     * @type {string}
     * @memberof AddFollowDto
     */
    destinationDevice: string;
    /**
     * 
     * @type {number}
     * @memberof AddFollowDto
     */
    destinationPin: number;
    /**
     * 
     * @type {boolean}
     * @memberof AddFollowDto
     */
    mirror?: boolean;
}

/**
 * Check if a given object implements the AddFollowDto interface.
 */
export function instanceOfAddFollowDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "followName" in value;
    isInstance = isInstance && "sourceDevice" in value;
    isInstance = isInstance && "sourcePin" in value;
    isInstance = isInstance && "destinationDevice" in value;
    isInstance = isInstance && "destinationPin" in value;

    return isInstance;
}

export function AddFollowDtoFromJSON(json: any): AddFollowDto {
    return AddFollowDtoFromJSONTyped(json, false);
}

export function AddFollowDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddFollowDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'disabled': !exists(json, 'disabled') ? undefined : json['disabled'],
        'followName': json['followName'],
        'sourceDevice': json['sourceDevice'],
        'sourcePin': json['sourcePin'],
        'destinationDevice': json['destinationDevice'],
        'destinationPin': json['destinationPin'],
        'mirror': !exists(json, 'mirror') ? undefined : json['mirror'],
    };
}

export function AddFollowDtoToJSON(value?: AddFollowDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'disabled': value.disabled,
        'followName': value.followName,
        'sourceDevice': value.sourceDevice,
        'sourcePin': value.sourcePin,
        'destinationDevice': value.destinationDevice,
        'destinationPin': value.destinationPin,
        'mirror': value.mirror,
    };
}

