/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddPresetResult
 */
export interface AddPresetResult {
    /**
     * 
     * @type {boolean}
     * @memberof AddPresetResult
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AddPresetResult
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddPresetResult
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AddPresetResult
     */
    presetNumber?: string | null;
}

/**
 * Check if a given object implements the AddPresetResult interface.
 */
export function instanceOfAddPresetResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddPresetResultFromJSON(json: any): AddPresetResult {
    return AddPresetResultFromJSONTyped(json, false);
}

export function AddPresetResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddPresetResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'presetNumber': !exists(json, 'presetNumber') ? undefined : json['presetNumber'],
    };
}

export function AddPresetResultToJSON(value?: AddPresetResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'id': value.id,
        'presetNumber': value.presetNumber,
    };
}

