/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { WebhookHeaders } from './WebhookHeaders';
import {
    WebhookHeadersFromJSON,
    WebhookHeadersFromJSONTyped,
    WebhookHeadersToJSON,
} from './WebhookHeaders';

/**
 * 
 * @export
 * @interface AddWebhookDto
 */
export interface AddWebhookDto {
    /**
     * 
     * @type {boolean}
     * @memberof AddWebhookDto
     */
    disabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AddWebhookDto
     */
    webhookUrl: string;
    /**
     * 
     * @type {Array<WebhookHeaders>}
     * @memberof AddWebhookDto
     */
    webhookHeaders?: Array<WebhookHeaders> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AddWebhookDto
     */
    properties: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AddWebhookDto
     */
    devices: Array<string>;
}

/**
 * Check if a given object implements the AddWebhookDto interface.
 */
export function instanceOfAddWebhookDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "webhookUrl" in value;
    isInstance = isInstance && "properties" in value;
    isInstance = isInstance && "devices" in value;

    return isInstance;
}

export function AddWebhookDtoFromJSON(json: any): AddWebhookDto {
    return AddWebhookDtoFromJSONTyped(json, false);
}

export function AddWebhookDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddWebhookDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'disabled': !exists(json, 'disabled') ? undefined : json['disabled'],
        'webhookUrl': json['webhookUrl'],
        'webhookHeaders': !exists(json, 'webhookHeaders') ? undefined : (json['webhookHeaders'] === null ? null : (json['webhookHeaders'] as Array<any>).map(WebhookHeadersFromJSON)),
        'properties': json['properties'],
        'devices': json['devices'],
    };
}

export function AddWebhookDtoToJSON(value?: AddWebhookDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'disabled': value.disabled,
        'webhookUrl': value.webhookUrl,
        'webhookHeaders': value.webhookHeaders === undefined ? undefined : (value.webhookHeaders === null ? null : (value.webhookHeaders as Array<any>).map(WebhookHeadersToJSON)),
        'properties': value.properties,
        'devices': value.devices,
    };
}

