/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddWebhookResult
 */
export interface AddWebhookResult {
    /**
     * 
     * @type {boolean}
     * @memberof AddWebhookResult
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AddWebhookResult
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddWebhookResult
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AddWebhookResult
     */
    webhookNumber?: string | null;
}

/**
 * Check if a given object implements the AddWebhookResult interface.
 */
export function instanceOfAddWebhookResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddWebhookResultFromJSON(json: any): AddWebhookResult {
    return AddWebhookResultFromJSONTyped(json, false);
}

export function AddWebhookResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddWebhookResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'webhookNumber': !exists(json, 'webhookNumber') ? undefined : json['webhookNumber'],
    };
}

export function AddWebhookResultToJSON(value?: AddWebhookResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'id': value.id,
        'webhookNumber': value.webhookNumber,
    };
}

