/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { WebhookHeaders } from './WebhookHeaders';
import {
    WebhookHeadersFromJSON,
    WebhookHeadersFromJSONTyped,
    WebhookHeadersToJSON,
} from './WebhookHeaders';

/**
 * 
 * @export
 * @interface AllWebhooksDto
 */
export interface AllWebhooksDto {
    /**
     * 
     * @type {string}
     * @memberof AllWebhooksDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AllWebhooksDto
     */
    organisationId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AllWebhooksDto
     */
    disabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AllWebhooksDto
     */
    webhookNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AllWebhooksDto
     */
    createdBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof AllWebhooksDto
     */
    createdOn?: Date;
    /**
     * 
     * @type {number}
     * @memberof AllWebhooksDto
     */
    triggers?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof AllWebhooksDto
     */
    properties?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof AllWebhooksDto
     */
    webhookUrl?: string | null;
    /**
     * 
     * @type {Array<WebhookHeaders>}
     * @memberof AllWebhooksDto
     */
    webhookHeaders?: Array<WebhookHeaders> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AllWebhooksDto
     */
    devices?: Array<string> | null;
    /**
     * 
     * @type {Date}
     * @memberof AllWebhooksDto
     */
    lastCall?: Date | null;
}

/**
 * Check if a given object implements the AllWebhooksDto interface.
 */
export function instanceOfAllWebhooksDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AllWebhooksDtoFromJSON(json: any): AllWebhooksDto {
    return AllWebhooksDtoFromJSONTyped(json, false);
}

export function AllWebhooksDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllWebhooksDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'organisationId': !exists(json, 'organisationId') ? undefined : json['organisationId'],
        'disabled': !exists(json, 'disabled') ? undefined : json['disabled'],
        'webhookNumber': !exists(json, 'webhookNumber') ? undefined : json['webhookNumber'],
        'createdBy': !exists(json, 'createdBy') ? undefined : json['createdBy'],
        'createdOn': !exists(json, 'createdOn') ? undefined : (new Date(json['createdOn'])),
        'triggers': !exists(json, 'triggers') ? undefined : json['triggers'],
        'properties': !exists(json, 'properties') ? undefined : json['properties'],
        'webhookUrl': !exists(json, 'webhookUrl') ? undefined : json['webhookUrl'],
        'webhookHeaders': !exists(json, 'webhookHeaders') ? undefined : (json['webhookHeaders'] === null ? null : (json['webhookHeaders'] as Array<any>).map(WebhookHeadersFromJSON)),
        'devices': !exists(json, 'devices') ? undefined : json['devices'],
        'lastCall': !exists(json, 'lastCall') ? undefined : (json['lastCall'] === null ? null : new Date(json['lastCall'])),
    };
}

export function AllWebhooksDtoToJSON(value?: AllWebhooksDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'organisationId': value.organisationId,
        'disabled': value.disabled,
        'webhookNumber': value.webhookNumber,
        'createdBy': value.createdBy,
        'createdOn': value.createdOn === undefined ? undefined : (value.createdOn.toISOString()),
        'triggers': value.triggers,
        'properties': value.properties,
        'webhookUrl': value.webhookUrl,
        'webhookHeaders': value.webhookHeaders === undefined ? undefined : (value.webhookHeaders === null ? null : (value.webhookHeaders as Array<any>).map(WebhookHeadersToJSON)),
        'devices': value.devices,
        'lastCall': value.lastCall === undefined ? undefined : (value.lastCall === null ? null : value.lastCall.toISOString()),
    };
}

