/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AzureMessageContent
 */
export interface AzureMessageContent {
    /**
     * 
     * @type {boolean}
     * @memberof AzureMessageContent
     */
    success?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof AzureMessageContent
     */
    serial?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AzureMessageContent
     */
    property?: string | null;
    /**
     * 
     * @type {any}
     * @memberof AzureMessageContent
     */
    result?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AzureMessageContent
     */
    error?: any | null;
}

/**
 * Check if a given object implements the AzureMessageContent interface.
 */
export function instanceOfAzureMessageContent(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AzureMessageContentFromJSON(json: any): AzureMessageContent {
    return AzureMessageContentFromJSONTyped(json, false);
}

export function AzureMessageContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): AzureMessageContent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'serial': !exists(json, 'serial') ? undefined : json['serial'],
        'property': !exists(json, 'property') ? undefined : json['property'],
        'result': !exists(json, 'result') ? undefined : json['result'],
        'error': !exists(json, 'error') ? undefined : json['error'],
    };
}

export function AzureMessageContentToJSON(value?: AzureMessageContent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'serial': value.serial,
        'property': value.property,
        'result': value.result,
        'error': value.error,
    };
}

