/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AzureMessageContent } from './AzureMessageContent';
import {
    AzureMessageContentFromJSON,
    AzureMessageContentFromJSONTyped,
    AzureMessageContentToJSON,
} from './AzureMessageContent';

/**
 * 
 * @export
 * @interface AzureMessage
 */
export interface AzureMessage {
    /**
     * 
     * @type {Array<AzureMessageContent>}
     * @memberof AzureMessage
     */
    push?: Array<AzureMessageContent> | null;
    /**
     * 
     * @type {Array<AzureMessageContent>}
     * @memberof AzureMessage
     */
    response?: Array<AzureMessageContent> | null;
    /**
     * 
     * @type {Array<AzureMessageContent>}
     * @memberof AzureMessage
     */
    overflow?: Array<AzureMessageContent> | null;
}

/**
 * Check if a given object implements the AzureMessage interface.
 */
export function instanceOfAzureMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AzureMessageFromJSON(json: any): AzureMessage {
    return AzureMessageFromJSONTyped(json, false);
}

export function AzureMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): AzureMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'push': !exists(json, 'push') ? undefined : (json['push'] === null ? null : (json['push'] as Array<any>).map(AzureMessageContentFromJSON)),
        'response': !exists(json, 'response') ? undefined : (json['response'] === null ? null : (json['response'] as Array<any>).map(AzureMessageContentFromJSON)),
        'overflow': !exists(json, 'overflow') ? undefined : (json['overflow'] === null ? null : (json['overflow'] as Array<any>).map(AzureMessageContentFromJSON)),
    };
}

export function AzureMessageToJSON(value?: AzureMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'push': value.push === undefined ? undefined : (value.push === null ? null : (value.push as Array<any>).map(AzureMessageContentToJSON)),
        'response': value.response === undefined ? undefined : (value.response === null ? null : (value.response as Array<any>).map(AzureMessageContentToJSON)),
        'overflow': value.overflow === undefined ? undefined : (value.overflow === null ? null : (value.overflow as Array<any>).map(AzureMessageContentToJSON)),
    };
}

