/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClaimResult
 */
export interface ClaimResult {
    /**
     * 
     * @type {boolean}
     * @memberof ClaimResult
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ClaimResult
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ClaimResult
     */
    claimCode?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ClaimResult
     */
    claimExpiry?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ClaimResult
     */
    deviceKey?: string | null;
}

/**
 * Check if a given object implements the ClaimResult interface.
 */
export function instanceOfClaimResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ClaimResultFromJSON(json: any): ClaimResult {
    return ClaimResultFromJSONTyped(json, false);
}

export function ClaimResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClaimResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'claimCode': !exists(json, 'claimCode') ? undefined : json['claimCode'],
        'claimExpiry': !exists(json, 'claimExpiry') ? undefined : (json['claimExpiry'] === null ? null : new Date(json['claimExpiry'])),
        'deviceKey': !exists(json, 'deviceKey') ? undefined : json['deviceKey'],
    };
}

export function ClaimResultToJSON(value?: ClaimResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'claimCode': value.claimCode,
        'claimExpiry': value.claimExpiry === undefined ? undefined : (value.claimExpiry === null ? null : value.claimExpiry.toISOString()),
        'deviceKey': value.deviceKey,
    };
}

