/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const CloudReason = {
  PowerLoss: 0,
  DeviceRestarted: 1,
  GoingToSleep: 2,
  DeviceUpdated: 3,
  WifiRestarted: 4,
  CloudDisabled: 5,
} as const;
export type CloudReason = typeof CloudReason[keyof typeof CloudReason];

export function CloudReasonFromJSON(json: any): CloudReason {
  return CloudReasonFromJSONTyped(json, false);
}

export function CloudReasonFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CloudReason {
  return json as CloudReason;
}

export function CloudReasonToJSON(value?: CloudReason | null): any {
  return value as any;
}
