/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CommandDirection = {
    Outbound: 0,
    Inbound: 1
} as const;
export type CommandDirection = typeof CommandDirection[keyof typeof CommandDirection];


export function CommandDirectionFromJSON(json: any): CommandDirection {
    return CommandDirectionFromJSONTyped(json, false);
}

export function CommandDirectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommandDirection {
    return json as CommandDirection;
}

export function CommandDirectionToJSON(value?: CommandDirection | null): any {
    return value as any;
}

