/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DefaultWithId
 */
export interface DefaultWithId {
    /**
     * 
     * @type {boolean}
     * @memberof DefaultWithId
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DefaultWithId
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DefaultWithId
     */
    id?: string;
}

/**
 * Check if a given object implements the DefaultWithId interface.
 */
export function instanceOfDefaultWithId(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DefaultWithIdFromJSON(json: any): DefaultWithId {
    return DefaultWithIdFromJSONTyped(json, false);
}

export function DefaultWithIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefaultWithId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function DefaultWithIdToJSON(value?: DefaultWithId | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'id': value.id,
    };
}

