/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DefaultWithToken
 */
export interface DefaultWithToken {
    /**
     * 
     * @type {boolean}
     * @memberof DefaultWithToken
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DefaultWithToken
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DefaultWithToken
     */
    token?: string | null;
}

/**
 * Check if a given object implements the DefaultWithToken interface.
 */
export function instanceOfDefaultWithToken(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DefaultWithTokenFromJSON(json: any): DefaultWithToken {
    return DefaultWithTokenFromJSONTyped(json, false);
}

export function DefaultWithTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefaultWithToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'token': !exists(json, 'token') ? undefined : json['token'],
    };
}

export function DefaultWithTokenToJSON(value?: DefaultWithToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'token': value.token,
    };
}

