/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeviceBus
 */
export interface DeviceBus {
    /**
     * 
     * @type {number}
     * @memberof DeviceBus
     */
    protocol?: number;
}

/**
 * Check if a given object implements the DeviceBus interface.
 */
export function instanceOfDeviceBus(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DeviceBusFromJSON(json: any): DeviceBus {
    return DeviceBusFromJSONTyped(json, false);
}

export function DeviceBusFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceBus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'protocol': !exists(json, 'protocol') ? undefined : json['protocol'],
    };
}

export function DeviceBusToJSON(value?: DeviceBus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'protocol': value.protocol,
    };
}

