/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeviceRequest
 */
export interface DeviceRequest {
    /**
     * 
     * @type {boolean}
     * @memberof DeviceRequest
     */
    response?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DeviceRequest
     */
    serial: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof DeviceRequest
     */
    request: Array<any>;
}

/**
 * Check if a given object implements the DeviceRequest interface.
 */
export function instanceOfDeviceRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "serial" in value;
    isInstance = isInstance && "request" in value;

    return isInstance;
}

export function DeviceRequestFromJSON(json: any): DeviceRequest {
    return DeviceRequestFromJSONTyped(json, false);
}

export function DeviceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : json['response'],
        'serial': json['serial'],
        'request': json['request'],
    };
}

export function DeviceRequestToJSON(value?: DeviceRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': value.response,
        'serial': value.serial,
        'request': value.request,
    };
}

