/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CloudReason } from './CloudReason';
import {
    CloudReasonFromJSON,
    CloudReasonFromJSONTyped,
    CloudReasonToJSON,
} from './CloudReason';

/**
 * 
 * @export
 * @interface DeviceCloud
 */
export interface DeviceCloud {
    /**
     * 
     * @type {boolean}
     * @memberof DeviceCloud
     */
    enabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DeviceCloud
     */
    connected?: boolean;
    /**
     * 
     * @type {CloudReason}
     * @memberof DeviceCloud
     */
    reason?: CloudReason;
}

/**
 * Check if a given object implements the DeviceCloud interface.
 */
export function instanceOfDeviceCloud(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DeviceCloudFromJSON(json: any): DeviceCloud {
    return DeviceCloudFromJSONTyped(json, false);
}

export function DeviceCloudFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceCloud {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
        'connected': !exists(json, 'connected') ? undefined : json['connected'],
        'reason': !exists(json, 'reason') ? undefined : CloudReasonFromJSON(json['reason']),
    };
}

export function DeviceCloudToJSON(value?: DeviceCloud | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'enabled': value.enabled,
        'connected': value.connected,
        'reason': CloudReasonToJSON(value.reason),
    };
}

