/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DevicePower
 */
export interface DevicePower {
    /**
     * 
     * @type {number}
     * @memberof DevicePower
     */
    current?: number;
    /**
     * 
     * @type {number}
     * @memberof DevicePower
     */
    voltage?: number;
    /**
     * 
     * @type {number}
     * @memberof DevicePower
     */
    source?: number;
}

/**
 * Check if a given object implements the DevicePower interface.
 */
export function instanceOfDevicePower(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DevicePowerFromJSON(json: any): DevicePower {
    return DevicePowerFromJSONTyped(json, false);
}

export function DevicePowerFromJSONTyped(json: any, ignoreDiscriminator: boolean): DevicePower {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'current': !exists(json, 'current') ? undefined : json['current'],
        'voltage': !exists(json, 'voltage') ? undefined : json['voltage'],
        'source': !exists(json, 'source') ? undefined : json['source'],
    };
}

export function DevicePowerToJSON(value?: DevicePower | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'current': value.current,
        'voltage': value.voltage,
        'source': value.source,
    };
}

