/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeviceVersion
 */
export interface DeviceVersion {
    /**
     * 
     * @type {string}
     * @memberof DeviceVersion
     */
    hardware?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceVersion
     */
    software?: string | null;
}

/**
 * Check if a given object implements the DeviceVersion interface.
 */
export function instanceOfDeviceVersion(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DeviceVersionFromJSON(json: any): DeviceVersion {
    return DeviceVersionFromJSONTyped(json, false);
}

export function DeviceVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceVersion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hardware': !exists(json, 'hardware') ? undefined : json['hardware'],
        'software': !exists(json, 'software') ? undefined : json['software'],
    };
}

export function DeviceVersionToJSON(value?: DeviceVersion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hardware': value.hardware,
        'software': value.software,
    };
}

