/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeviceSupport
 */
export interface DeviceSupport {
    /**
     * 
     * @type {boolean}
     * @memberof DeviceSupport
     */
    enabled?: boolean | null;
}

/**
 * Check if a given object implements the DeviceSupport interface.
 */
export function instanceOfDeviceSupport(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DeviceSupportFromJSON(json: any): DeviceSupport {
    return DeviceSupportFromJSONTyped(json, false);
}

export function DeviceSupportFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceSupport {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
    };
}

export function DeviceSupportToJSON(value?: DeviceSupport | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'enabled': value.enabled,
    };
}

