/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PeblGateway } from './PeblGateway';
import {
    PeblGatewayFromJSON,
    PeblGatewayFromJSONTyped,
    PeblGatewayToJSON,
} from './PeblGateway';

/**
 * 
 * @export
 * @interface DevicePeblDto
 */
export interface DevicePeblDto {
    /**
     * 
     * @type {Array<PeblGateway>}
     * @memberof DevicePeblDto
     */
    gateway?: Array<PeblGateway> | null;
}

/**
 * Check if a given object implements the DevicePeblDto interface.
 */
export function instanceOfDevicePeblDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DevicePeblDtoFromJSON(json: any): DevicePeblDto {
    return DevicePeblDtoFromJSONTyped(json, false);
}

export function DevicePeblDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DevicePeblDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gateway': !exists(json, 'gateway') ? undefined : (json['gateway'] === null ? null : (json['gateway'] as Array<any>).map(PeblGatewayFromJSON)),
    };
}

export function DevicePeblDtoToJSON(value?: DevicePeblDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'gateway': value.gateway === undefined ? undefined : (value.gateway === null ? null : (value.gateway as Array<any>).map(PeblGatewayToJSON)),
    };
}

