/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AllWebhooksDto } from './AllWebhooksDto';
import {
    AllWebhooksDtoFromJSON,
    AllWebhooksDtoFromJSONTyped,
    AllWebhooksDtoToJSON,
} from './AllWebhooksDto';

/**
 * 
 * @export
 * @interface EngineWebhooksResponse
 */
export interface EngineWebhooksResponse {
    /**
     * 
     * @type {boolean}
     * @memberof EngineWebhooksResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof EngineWebhooksResponse
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof EngineWebhooksResponse
     */
    count?: number;
    /**
     * 
     * @type {Array<AllWebhooksDto>}
     * @memberof EngineWebhooksResponse
     */
    webhooks?: Array<AllWebhooksDto> | null;
}

/**
 * Check if a given object implements the EngineWebhooksResponse interface.
 */
export function instanceOfEngineWebhooksResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EngineWebhooksResponseFromJSON(json: any): EngineWebhooksResponse {
    return EngineWebhooksResponseFromJSONTyped(json, false);
}

export function EngineWebhooksResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EngineWebhooksResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'pageNumber': !exists(json, 'pageNumber') ? undefined : json['pageNumber'],
        'count': !exists(json, 'count') ? undefined : json['count'],
        'webhooks': !exists(json, 'webhooks') ? undefined : (json['webhooks'] === null ? null : (json['webhooks'] as Array<any>).map(AllWebhooksDtoFromJSON)),
    };
}

export function EngineWebhooksResponseToJSON(value?: EngineWebhooksResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'pageNumber': value.pageNumber,
        'count': value.count,
        'webhooks': value.webhooks === undefined ? undefined : (value.webhooks === null ? null : (value.webhooks as Array<any>).map(AllWebhooksDtoToJSON)),
    };
}

