/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GatewayGpio
 */
export interface GatewayGpio {
    /**
     * 
     * @type {Array<number>}
     * @memberof GatewayGpio
     */
    state?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof GatewayGpio
     */
    direction?: Array<number> | null;
}

/**
 * Check if a given object implements the GatewayGpio interface.
 */
export function instanceOfGatewayGpio(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GatewayGpioFromJSON(json: any): GatewayGpio {
    return GatewayGpioFromJSONTyped(json, false);
}

export function GatewayGpioFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayGpio {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'state': !exists(json, 'state') ? undefined : json['state'],
        'direction': !exists(json, 'direction') ? undefined : json['direction'],
    };
}

export function GatewayGpioToJSON(value?: GatewayGpio | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'state': value.state,
        'direction': value.direction,
    };
}

