/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NodeDetect } from './NodeDetect';
import {
    NodeDetectFromJSON,
    NodeDetectFromJSONTyped,
    NodeDetectToJSON,
} from './NodeDetect';

/**
 * 
 * @export
 * @interface GatewayNode
 */
export interface GatewayNode {
    /**
     * 
     * @type {Array<NodeDetect>}
     * @memberof GatewayNode
     */
    detect?: Array<NodeDetect> | null;
}

/**
 * Check if a given object implements the GatewayNode interface.
 */
export function instanceOfGatewayNode(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GatewayNodeFromJSON(json: any): GatewayNode {
    return GatewayNodeFromJSONTyped(json, false);
}

export function GatewayNodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayNode {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'detect': !exists(json, 'detect') ? undefined : (json['detect'] === null ? null : (json['detect'] as Array<any>).map(NodeDetectFromJSON)),
    };
}

export function GatewayNodeToJSON(value?: GatewayNode | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'detect': value.detect === undefined ? undefined : (value.detect === null ? null : (value.detect as Array<any>).map(NodeDetectToJSON)),
    };
}

