/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NetworkIp } from './NetworkIp';
import {
    NetworkIpFromJSON,
    NetworkIpFromJSONTyped,
    NetworkIpToJSON,
} from './NetworkIp';
import type { NetworkMac } from './NetworkMac';
import {
    NetworkMacFromJSON,
    NetworkMacFromJSONTyped,
    NetworkMacToJSON,
} from './NetworkMac';

/**
 * 
 * @export
 * @interface GatewayNetwork
 */
export interface GatewayNetwork {
    /**
     * 
     * @type {NetworkIp}
     * @memberof GatewayNetwork
     */
    ip?: NetworkIp;
    /**
     * 
     * @type {NetworkMac}
     * @memberof GatewayNetwork
     */
    mac?: NetworkMac;
}

/**
 * Check if a given object implements the GatewayNetwork interface.
 */
export function instanceOfGatewayNetwork(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GatewayNetworkFromJSON(json: any): GatewayNetwork {
    return GatewayNetworkFromJSONTyped(json, false);
}

export function GatewayNetworkFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayNetwork {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ip': !exists(json, 'ip') ? undefined : NetworkIpFromJSON(json['ip']),
        'mac': !exists(json, 'mac') ? undefined : NetworkMacFromJSON(json['mac']),
    };
}

export function GatewayNetworkToJSON(value?: GatewayNetwork | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ip': NetworkIpToJSON(value.ip),
        'mac': NetworkMacToJSON(value.mac),
    };
}

