/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetProfileResponse
 */
export interface GetProfileResponse {
    /**
     * 
     * @type {string}
     * @memberof GetProfileResponse
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetProfileResponse
     */
    disabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetProfileResponse
     */
    forename?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetProfileResponse
     */
    surname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetProfileResponse
     */
    userHandle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetProfileResponse
     */
    email?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof GetProfileResponse
     */
    emailVerified?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetProfileResponse
     */
    mobile?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetProfileResponse
     */
    telephone?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof GetProfileResponse
     */
    marketing?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetProfileResponse
     */
    mfaEnabled?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof GetProfileResponse
     */
    lastLogin?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof GetProfileResponse
     */
    dateRegistered?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof GetProfileResponse
     */
    defaultOrganisation?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetProfileResponse
     */
    lastUsedOrganisation?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof GetProfileResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the GetProfileResponse interface.
 */
export function instanceOfGetProfileResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetProfileResponseFromJSON(json: any): GetProfileResponse {
    return GetProfileResponseFromJSONTyped(json, false);
}

export function GetProfileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProfileResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'disabled': !exists(json, 'disabled') ? undefined : json['disabled'],
        'forename': !exists(json, 'forename') ? undefined : json['forename'],
        'surname': !exists(json, 'surname') ? undefined : json['surname'],
        'userHandle': !exists(json, 'userHandle') ? undefined : json['userHandle'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'emailVerified': !exists(json, 'emailVerified') ? undefined : json['emailVerified'],
        'mobile': !exists(json, 'mobile') ? undefined : json['mobile'],
        'telephone': !exists(json, 'telephone') ? undefined : json['telephone'],
        'marketing': !exists(json, 'marketing') ? undefined : json['marketing'],
        'mfaEnabled': !exists(json, 'mfaEnabled') ? undefined : json['mfaEnabled'],
        'lastLogin': !exists(json, 'lastLogin') ? undefined : (json['lastLogin'] === null ? null : new Date(json['lastLogin'])),
        'dateRegistered': !exists(json, 'dateRegistered') ? undefined : (json['dateRegistered'] === null ? null : new Date(json['dateRegistered'])),
        'defaultOrganisation': !exists(json, 'defaultOrganisation') ? undefined : json['defaultOrganisation'],
        'lastUsedOrganisation': !exists(json, 'lastUsedOrganisation') ? undefined : json['lastUsedOrganisation'],
        'success': !exists(json, 'success') ? undefined : json['success'],
    };
}

export function GetProfileResponseToJSON(value?: GetProfileResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'disabled': value.disabled,
        'forename': value.forename,
        'surname': value.surname,
        'userHandle': value.userHandle,
        'email': value.email,
        'emailVerified': value.emailVerified,
        'mobile': value.mobile,
        'telephone': value.telephone,
        'marketing': value.marketing,
        'mfaEnabled': value.mfaEnabled,
        'lastLogin': value.lastLogin === undefined ? undefined : (value.lastLogin === null ? null : value.lastLogin.toISOString()),
        'dateRegistered': value.dateRegistered === undefined ? undefined : (value.dateRegistered === null ? null : value.dateRegistered.toISOString()),
        'defaultOrganisation': value.defaultOrganisation,
        'lastUsedOrganisation': value.lastUsedOrganisation,
        'success': value.success,
    };
}

