/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface I2cSetup
 */
export interface I2cSetup {
    /**
     * 
     * @type {number}
     * @memberof I2cSetup
     */
    speed?: number;
    /**
     * 
     * @type {boolean}
     * @memberof I2cSetup
     */
    scan?: boolean;
}

/**
 * Check if a given object implements the I2cSetup interface.
 */
export function instanceOfI2cSetup(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function I2cSetupFromJSON(json: any): I2cSetup {
    return I2cSetupFromJSONTyped(json, false);
}

export function I2cSetupFromJSONTyped(json: any, ignoreDiscriminator: boolean): I2cSetup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'speed': !exists(json, 'speed') ? undefined : json['speed'],
        'scan': !exists(json, 'scan') ? undefined : json['scan'],
    };
}

export function I2cSetupToJSON(value?: I2cSetup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'speed': value.speed,
        'scan': value.scan,
    };
}

