/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InviteUserDto
 */
export interface InviteUserDto {
    /**
     * 
     * @type {string}
     * @memberof InviteUserDto
     */
    forename: string;
    /**
     * 
     * @type {string}
     * @memberof InviteUserDto
     */
    surname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InviteUserDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof InviteUserDto
     */
    roleId: string;
}

/**
 * Check if a given object implements the InviteUserDto interface.
 */
export function instanceOfInviteUserDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "forename" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "roleId" in value;

    return isInstance;
}

export function InviteUserDtoFromJSON(json: any): InviteUserDto {
    return InviteUserDtoFromJSONTyped(json, false);
}

export function InviteUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteUserDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'forename': json['forename'],
        'surname': !exists(json, 'surname') ? undefined : json['surname'],
        'email': json['email'],
        'roleId': json['roleId'],
    };
}

export function InviteUserDtoToJSON(value?: InviteUserDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'forename': value.forename,
        'surname': value.surname,
        'email': value.email,
        'roleId': value.roleId,
    };
}

