/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const LocationPort = {
    A: 0,
    B: 1
} as const;
export type LocationPort = typeof LocationPort[keyof typeof LocationPort];


export function LocationPortFromJSON(json: any): LocationPort {
    return LocationPortFromJSONTyped(json, false);
}

export function LocationPortFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationPort {
    return json as LocationPort;
}

export function LocationPortToJSON(value?: LocationPort | null): any {
    return value as any;
}

