/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const MessageType = {
  System: 0,
  Push: 1,
  Response: 2,
  Overflow: 3,
  Request: 4,
} as const;
export type MessageType = typeof MessageType[keyof typeof MessageType];

export function MessageTypeFromJSON(json: any): MessageType {
  return MessageTypeFromJSONTyped(json, false);
}

export function MessageTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MessageType {
  return json as MessageType;
}

export function MessageTypeToJSON(value?: MessageType | null): any {
  return value as any;
}
