/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MqttStatus
 */
export interface MqttStatus {
    /**
     * 
     * @type {boolean}
     * @memberof MqttStatus
     */
    enabled?: boolean;
}

/**
 * Check if a given object implements the MqttStatus interface.
 */
export function instanceOfMqttStatus(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MqttStatusFromJSON(json: any): MqttStatus {
    return MqttStatusFromJSONTyped(json, false);
}

export function MqttStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): MqttStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
    };
}

export function MqttStatusToJSON(value?: MqttStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'enabled': value.enabled,
    };
}

