/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MqttDeviceResponse
 */
export interface MqttDeviceResponse {
    /**
     * 
     * @type {boolean}
     * @memberof MqttDeviceResponse
     */
    success?: boolean;
    /**
     * 
     * @type {Array<any>}
     * @memberof MqttDeviceResponse
     */
    response?: Array<any> | null;
    /**
     * 
     * @type {Array<any>}
     * @memberof MqttDeviceResponse
     */
    error?: Array<any> | null;
}

/**
 * Check if a given object implements the MqttDeviceResponse interface.
 */
export function instanceOfMqttDeviceResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MqttDeviceResponseFromJSON(json: any): MqttDeviceResponse {
    return MqttDeviceResponseFromJSONTyped(json, false);
}

export function MqttDeviceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MqttDeviceResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'response': !exists(json, 'response') ? undefined : json['response'],
        'error': !exists(json, 'error') ? undefined : json['error'],
    };
}

export function MqttDeviceResponseToJSON(value?: MqttDeviceResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'response': value.response,
        'error': value.error,
    };
}

