/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NetworkMac
 */
export interface NetworkMac {
    /**
     * 
     * @type {string}
     * @memberof NetworkMac
     */
    ap?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NetworkMac
     */
    station?: string | null;
}

/**
 * Check if a given object implements the NetworkMac interface.
 */
export function instanceOfNetworkMac(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NetworkMacFromJSON(json: any): NetworkMac {
    return NetworkMacFromJSONTyped(json, false);
}

export function NetworkMacFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkMac {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ap': !exists(json, 'ap') ? undefined : json['ap'],
        'station': !exists(json, 'station') ? undefined : json['station'],
    };
}

export function NetworkMacToJSON(value?: NetworkMac | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ap': value.ap,
        'station': value.station,
    };
}

