/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewOrganisationTokenDto
 */
export interface NewOrganisationTokenDto {
    /**
     * 
     * @type {Date}
     * @memberof NewOrganisationTokenDto
     */
    expiry?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof NewOrganisationTokenDto
     */
    tokenName: string;
    /**
     * 
     * @type {string}
     * @memberof NewOrganisationTokenDto
     */
    roleId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof NewOrganisationTokenDto
     */
    assignedUsers?: Array<string> | null;
}

/**
 * Check if a given object implements the NewOrganisationTokenDto interface.
 */
export function instanceOfNewOrganisationTokenDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "tokenName" in value;
    isInstance = isInstance && "roleId" in value;

    return isInstance;
}

export function NewOrganisationTokenDtoFromJSON(json: any): NewOrganisationTokenDto {
    return NewOrganisationTokenDtoFromJSONTyped(json, false);
}

export function NewOrganisationTokenDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewOrganisationTokenDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'expiry': !exists(json, 'expiry') ? undefined : (json['expiry'] === null ? null : new Date(json['expiry'])),
        'tokenName': json['tokenName'],
        'roleId': json['roleId'],
        'assignedUsers': !exists(json, 'assignedUsers') ? undefined : json['assignedUsers'],
    };
}

export function NewOrganisationTokenDtoToJSON(value?: NewOrganisationTokenDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'expiry': value.expiry === undefined ? undefined : (value.expiry === null ? null : value.expiry.toISOString()),
        'tokenName': value.tokenName,
        'roleId': value.roleId,
        'assignedUsers': value.assignedUsers,
    };
}

