/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewUserTokenDto
 */
export interface NewUserTokenDto {
    /**
     * 
     * @type {Date}
     * @memberof NewUserTokenDto
     */
    expiry?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof NewUserTokenDto
     */
    tokenName: string;
    /**
     * 
     * @type {string}
     * @memberof NewUserTokenDto
     */
    organisationId?: string | null;
}

/**
 * Check if a given object implements the NewUserTokenDto interface.
 */
export function instanceOfNewUserTokenDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "tokenName" in value;

    return isInstance;
}

export function NewUserTokenDtoFromJSON(json: any): NewUserTokenDto {
    return NewUserTokenDtoFromJSONTyped(json, false);
}

export function NewUserTokenDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewUserTokenDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'expiry': !exists(json, 'expiry') ? undefined : (json['expiry'] === null ? null : new Date(json['expiry'])),
        'tokenName': json['tokenName'],
        'organisationId': !exists(json, 'organisationId') ? undefined : json['organisationId'],
    };
}

export function NewUserTokenDtoToJSON(value?: NewUserTokenDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'expiry': value.expiry === undefined ? undefined : (value.expiry === null ? null : value.expiry.toISOString()),
        'tokenName': value.tokenName,
        'organisationId': value.organisationId,
    };
}

