/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodeDetect
 */
export interface NodeDetect {
    /**
     * 
     * @type {string}
     * @memberof NodeDetect
     */
    serial?: string | null;
    /**
     * 
     * @type {number}
     * @memberof NodeDetect
     */
    address?: number;
}

/**
 * Check if a given object implements the NodeDetect interface.
 */
export function instanceOfNodeDetect(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NodeDetectFromJSON(json: any): NodeDetect {
    return NodeDetectFromJSONTyped(json, false);
}

export function NodeDetectFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeDetect {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'serial': !exists(json, 'serial') ? undefined : json['serial'],
        'address': !exists(json, 'address') ? undefined : json['address'],
    };
}

export function NodeDetectToJSON(value?: NodeDetect | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'serial': value.serial,
        'address': value.address,
    };
}

