/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodeData
 */
export interface NodeData {
    /**
     * 
     * @type {string}
     * @memberof NodeData
     */
    value?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof NodeData
     */
    timestamp?: Date | null;
}

/**
 * Check if a given object implements the NodeData interface.
 */
export function instanceOfNodeData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NodeDataFromJSON(json: any): NodeData {
    return NodeDataFromJSONTyped(json, false);
}

export function NodeDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : json['value'],
        'timestamp': !exists(json, 'timestamp') ? undefined : (json['timestamp'] === null ? null : new Date(json['timestamp'])),
    };
}

export function NodeDataToJSON(value?: NodeData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
        'timestamp': value.timestamp === undefined ? undefined : (value.timestamp === null ? null : value.timestamp.toISOString()),
    };
}

