/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodeAddress
 */
export interface NodeAddress {
    /**
     * 
     * @type {boolean}
     * @memberof NodeAddress
     */
    _static?: boolean;
    /**
     * 
     * @type {number}
     * @memberof NodeAddress
     */
    value?: number;
}

/**
 * Check if a given object implements the NodeAddress interface.
 */
export function instanceOfNodeAddress(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NodeAddressFromJSON(json: any): NodeAddress {
    return NodeAddressFromJSONTyped(json, false);
}

export function NodeAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeAddress {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '_static': !exists(json, 'static') ? undefined : json['static'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function NodeAddressToJSON(value?: NodeAddress | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'static': value._static,
        'value': value.value,
    };
}

