/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganisationTenantDto
 */
export interface OrganisationTenantDto {
    /**
     * 
     * @type {string}
     * @memberof OrganisationTenantDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationTenantDto
     */
    organisationNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganisationTenantDto
     */
    organisationName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganisationTenantDto
     */
    subscriptionId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof OrganisationTenantDto
     */
    isBusiness?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrganisationTenantDto
     */
    trialUsed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrganisationTenantDto
     */
    disabled?: boolean;
}

/**
 * Check if a given object implements the OrganisationTenantDto interface.
 */
export function instanceOfOrganisationTenantDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrganisationTenantDtoFromJSON(json: any): OrganisationTenantDto {
    return OrganisationTenantDtoFromJSONTyped(json, false);
}

export function OrganisationTenantDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationTenantDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'organisationNumber': !exists(json, 'organisationNumber') ? undefined : json['organisationNumber'],
        'organisationName': !exists(json, 'organisationName') ? undefined : json['organisationName'],
        'subscriptionId': !exists(json, 'subscriptionId') ? undefined : json['subscriptionId'],
        'isBusiness': !exists(json, 'isBusiness') ? undefined : json['isBusiness'],
        'trialUsed': !exists(json, 'trialUsed') ? undefined : json['trialUsed'],
        'disabled': !exists(json, 'disabled') ? undefined : json['disabled'],
    };
}

export function OrganisationTenantDtoToJSON(value?: OrganisationTenantDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'organisationNumber': value.organisationNumber,
        'organisationName': value.organisationName,
        'subscriptionId': value.subscriptionId,
        'isBusiness': value.isBusiness,
        'trialUsed': value.trialUsed,
        'disabled': value.disabled,
    };
}

