/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OrganisationAddressesDto } from './OrganisationAddressesDto';
import {
    OrganisationAddressesDtoFromJSON,
    OrganisationAddressesDtoFromJSONTyped,
    OrganisationAddressesDtoToJSON,
} from './OrganisationAddressesDto';

/**
 * 
 * @export
 * @interface OrganisationAddressResponse
 */
export interface OrganisationAddressResponse {
    /**
     * 
     * @type {boolean}
     * @memberof OrganisationAddressResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof OrganisationAddressResponse
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof OrganisationAddressResponse
     */
    count?: number;
    /**
     * 
     * @type {Array<OrganisationAddressesDto>}
     * @memberof OrganisationAddressResponse
     */
    addresses?: Array<OrganisationAddressesDto> | null;
}

/**
 * Check if a given object implements the OrganisationAddressResponse interface.
 */
export function instanceOfOrganisationAddressResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrganisationAddressResponseFromJSON(json: any): OrganisationAddressResponse {
    return OrganisationAddressResponseFromJSONTyped(json, false);
}

export function OrganisationAddressResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationAddressResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'pageNumber': !exists(json, 'pageNumber') ? undefined : json['pageNumber'],
        'count': !exists(json, 'count') ? undefined : json['count'],
        'addresses': !exists(json, 'addresses') ? undefined : (json['addresses'] === null ? null : (json['addresses'] as Array<any>).map(OrganisationAddressesDtoFromJSON)),
    };
}

export function OrganisationAddressResponseToJSON(value?: OrganisationAddressResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'pageNumber': value.pageNumber,
        'count': value.count,
        'addresses': value.addresses === undefined ? undefined : (value.addresses === null ? null : (value.addresses as Array<any>).map(OrganisationAddressesDtoToJSON)),
    };
}

