/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganisationUsersDto
 */
export interface OrganisationUsersDto {
    /**
     * 
     * @type {string}
     * @memberof OrganisationUsersDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationUsersDto
     */
    forename?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganisationUsersDto
     */
    surname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganisationUsersDto
     */
    userHandle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganisationUsersDto
     */
    email?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof OrganisationUsersDto
     */
    emailVerified?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OrganisationUsersDto
     */
    roleId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof OrganisationUsersDto
     */
    disabled?: boolean;
}

/**
 * Check if a given object implements the OrganisationUsersDto interface.
 */
export function instanceOfOrganisationUsersDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrganisationUsersDtoFromJSON(json: any): OrganisationUsersDto {
    return OrganisationUsersDtoFromJSONTyped(json, false);
}

export function OrganisationUsersDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationUsersDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'forename': !exists(json, 'forename') ? undefined : json['forename'],
        'surname': !exists(json, 'surname') ? undefined : json['surname'],
        'userHandle': !exists(json, 'userHandle') ? undefined : json['userHandle'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'emailVerified': !exists(json, 'emailVerified') ? undefined : json['emailVerified'],
        'roleId': !exists(json, 'roleId') ? undefined : json['roleId'],
        'disabled': !exists(json, 'disabled') ? undefined : json['disabled'],
    };
}

export function OrganisationUsersDtoToJSON(value?: OrganisationUsersDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'forename': value.forename,
        'surname': value.surname,
        'userHandle': value.userHandle,
        'email': value.email,
        'emailVerified': value.emailVerified,
        'roleId': value.roleId,
        'disabled': value.disabled,
    };
}

