/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganisationPresetsDto
 */
export interface OrganisationPresetsDto {
    /**
     * 
     * @type {string}
     * @memberof OrganisationPresetsDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationPresetsDto
     */
    presetNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganisationPresetsDto
     */
    presetName?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof OrganisationPresetsDto
     */
    disabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OrganisationPresetsDto
     */
    ssid?: string | null;
}

/**
 * Check if a given object implements the OrganisationPresetsDto interface.
 */
export function instanceOfOrganisationPresetsDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrganisationPresetsDtoFromJSON(json: any): OrganisationPresetsDto {
    return OrganisationPresetsDtoFromJSONTyped(json, false);
}

export function OrganisationPresetsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationPresetsDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'presetNumber': !exists(json, 'presetNumber') ? undefined : json['presetNumber'],
        'presetName': !exists(json, 'presetName') ? undefined : json['presetName'],
        'disabled': !exists(json, 'disabled') ? undefined : json['disabled'],
        'ssid': !exists(json, 'ssid') ? undefined : json['ssid'],
    };
}

export function OrganisationPresetsDtoToJSON(value?: OrganisationPresetsDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'presetNumber': value.presetNumber,
        'presetName': value.presetName,
        'disabled': value.disabled,
        'ssid': value.ssid,
    };
}

