/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PartnerContact
 */
export interface PartnerContact {
    /**
     * 
     * @type {string}
     * @memberof PartnerContact
     */
    forename?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PartnerContact
     */
    surname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PartnerContact
     */
    userHandle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PartnerContact
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PartnerContact
     */
    mobile?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PartnerContact
     */
    telephone?: string | null;
}

/**
 * Check if a given object implements the PartnerContact interface.
 */
export function instanceOfPartnerContact(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PartnerContactFromJSON(json: any): PartnerContact {
    return PartnerContactFromJSONTyped(json, false);
}

export function PartnerContactFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerContact {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'forename': !exists(json, 'forename') ? undefined : json['forename'],
        'surname': !exists(json, 'surname') ? undefined : json['surname'],
        'userHandle': !exists(json, 'userHandle') ? undefined : json['userHandle'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'mobile': !exists(json, 'mobile') ? undefined : json['mobile'],
        'telephone': !exists(json, 'telephone') ? undefined : json['telephone'],
    };
}

export function PartnerContactToJSON(value?: PartnerContact | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'forename': value.forename,
        'surname': value.surname,
        'userHandle': value.userHandle,
        'email': value.email,
        'mobile': value.mobile,
        'telephone': value.telephone,
    };
}

