/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchFollowRequest
 */
export interface PatchFollowRequest {
    /**
     * 
     * @type {boolean}
     * @memberof PatchFollowRequest
     */
    disabled?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof PatchFollowRequest
     */
    followName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchFollowRequest
     */
    sourceDevice?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchFollowRequest
     */
    sourcePin?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PatchFollowRequest
     */
    destinationDevice?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchFollowRequest
     */
    destinationPin?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchFollowRequest
     */
    mirror?: boolean | null;
}

/**
 * Check if a given object implements the PatchFollowRequest interface.
 */
export function instanceOfPatchFollowRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchFollowRequestFromJSON(json: any): PatchFollowRequest {
    return PatchFollowRequestFromJSONTyped(json, false);
}

export function PatchFollowRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchFollowRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'disabled': !exists(json, 'disabled') ? undefined : json['disabled'],
        'followName': !exists(json, 'followName') ? undefined : json['followName'],
        'sourceDevice': !exists(json, 'sourceDevice') ? undefined : json['sourceDevice'],
        'sourcePin': !exists(json, 'sourcePin') ? undefined : json['sourcePin'],
        'destinationDevice': !exists(json, 'destinationDevice') ? undefined : json['destinationDevice'],
        'destinationPin': !exists(json, 'destinationPin') ? undefined : json['destinationPin'],
        'mirror': !exists(json, 'mirror') ? undefined : json['mirror'],
    };
}

export function PatchFollowRequestToJSON(value?: PatchFollowRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'disabled': value.disabled,
        'followName': value.followName,
        'sourceDevice': value.sourceDevice,
        'sourcePin': value.sourcePin,
        'destinationDevice': value.destinationDevice,
        'destinationPin': value.destinationPin,
        'mirror': value.mirror,
    };
}

