/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchAddressRequest
 */
export interface PatchAddressRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchAddressRequest
     */
    line1?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchAddressRequest
     */
    line2?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchAddressRequest
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchAddressRequest
     */
    county?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchAddressRequest
     */
    postcode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchAddressRequest
     */
    country?: string | null;
}

/**
 * Check if a given object implements the PatchAddressRequest interface.
 */
export function instanceOfPatchAddressRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchAddressRequestFromJSON(json: any): PatchAddressRequest {
    return PatchAddressRequestFromJSONTyped(json, false);
}

export function PatchAddressRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchAddressRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'line1': !exists(json, 'line1') ? undefined : json['line1'],
        'line2': !exists(json, 'line2') ? undefined : json['line2'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'county': !exists(json, 'county') ? undefined : json['county'],
        'postcode': !exists(json, 'postcode') ? undefined : json['postcode'],
        'country': !exists(json, 'country') ? undefined : json['country'],
    };
}

export function PatchAddressRequestToJSON(value?: PatchAddressRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'line1': value.line1,
        'line2': value.line2,
        'city': value.city,
        'county': value.county,
        'postcode': value.postcode,
        'country': value.country,
    };
}

