/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DeviceSupport } from './DeviceSupport';
import {
    DeviceSupportFromJSON,
    DeviceSupportFromJSONTyped,
    DeviceSupportToJSON,
} from './DeviceSupport';

/**
 * 
 * @export
 * @interface PatchDevice
 */
export interface PatchDevice {
    /**
     * 
     * @type {string}
     * @memberof PatchDevice
     */
    name?: string | null;
    /**
     * 
     * @type {DeviceSupport}
     * @memberof PatchDevice
     */
    support?: DeviceSupport;
}

/**
 * Check if a given object implements the PatchDevice interface.
 */
export function instanceOfPatchDevice(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchDeviceFromJSON(json: any): PatchDevice {
    return PatchDeviceFromJSONTyped(json, false);
}

export function PatchDeviceFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchDevice {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'support': !exists(json, 'support') ? undefined : DeviceSupportFromJSON(json['support']),
    };
}

export function PatchDeviceToJSON(value?: PatchDevice | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'support': DeviceSupportToJSON(value.support),
    };
}

