/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchUserRequest
 */
export interface PatchUserRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchUserRequest
     */
    forename?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchUserRequest
     */
    surname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchUserRequest
     */
    mobile?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchUserRequest
     */
    telephone?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchUserRequest
     */
    marketing?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof PatchUserRequest
     */
    defaultOrganisation?: string | null;
}

/**
 * Check if a given object implements the PatchUserRequest interface.
 */
export function instanceOfPatchUserRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchUserRequestFromJSON(json: any): PatchUserRequest {
    return PatchUserRequestFromJSONTyped(json, false);
}

export function PatchUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchUserRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'forename': !exists(json, 'forename') ? undefined : json['forename'],
        'surname': !exists(json, 'surname') ? undefined : json['surname'],
        'mobile': !exists(json, 'mobile') ? undefined : json['mobile'],
        'telephone': !exists(json, 'telephone') ? undefined : json['telephone'],
        'marketing': !exists(json, 'marketing') ? undefined : json['marketing'],
        'defaultOrganisation': !exists(json, 'defaultOrganisation') ? undefined : json['defaultOrganisation'],
    };
}

export function PatchUserRequestToJSON(value?: PatchUserRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'forename': value.forename,
        'surname': value.surname,
        'mobile': value.mobile,
        'telephone': value.telephone,
        'marketing': value.marketing,
        'defaultOrganisation': value.defaultOrganisation,
    };
}

