/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PatchDevice } from './PatchDevice';
import {
    PatchDeviceFromJSON,
    PatchDeviceFromJSONTyped,
    PatchDeviceToJSON,
} from './PatchDevice';

/**
 * 
 * @export
 * @interface PatchGateway
 */
export interface PatchGateway {
    /**
     * 
     * @type {PatchDevice}
     * @memberof PatchGateway
     */
    device?: PatchDevice;
}

/**
 * Check if a given object implements the PatchGateway interface.
 */
export function instanceOfPatchGateway(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchGatewayFromJSON(json: any): PatchGateway {
    return PatchGatewayFromJSONTyped(json, false);
}

export function PatchGatewayFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchGateway {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'device': !exists(json, 'device') ? undefined : PatchDeviceFromJSON(json['device']),
    };
}

export function PatchGatewayToJSON(value?: PatchGateway | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'device': PatchDeviceToJSON(value.device),
    };
}

