/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserOrganisationsDto } from './UserOrganisationsDto';
import {
    UserOrganisationsDtoFromJSON,
    UserOrganisationsDtoFromJSONTyped,
    UserOrganisationsDtoToJSON,
} from './UserOrganisationsDto';

/**
 * 
 * @export
 * @interface PortalUserOrganisationsDto
 */
export interface PortalUserOrganisationsDto {
    /**
     * 
     * @type {boolean}
     * @memberof PortalUserOrganisationsDto
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PortalUserOrganisationsDto
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof PortalUserOrganisationsDto
     */
    count?: number;
    /**
     * 
     * @type {Array<UserOrganisationsDto>}
     * @memberof PortalUserOrganisationsDto
     */
    organisations?: Array<UserOrganisationsDto> | null;
}

/**
 * Check if a given object implements the PortalUserOrganisationsDto interface.
 */
export function instanceOfPortalUserOrganisationsDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PortalUserOrganisationsDtoFromJSON(json: any): PortalUserOrganisationsDto {
    return PortalUserOrganisationsDtoFromJSONTyped(json, false);
}

export function PortalUserOrganisationsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortalUserOrganisationsDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'pageNumber': !exists(json, 'pageNumber') ? undefined : json['pageNumber'],
        'count': !exists(json, 'count') ? undefined : json['count'],
        'organisations': !exists(json, 'organisations') ? undefined : (json['organisations'] === null ? null : (json['organisations'] as Array<any>).map(UserOrganisationsDtoFromJSON)),
    };
}

export function PortalUserOrganisationsDtoToJSON(value?: PortalUserOrganisationsDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'pageNumber': value.pageNumber,
        'count': value.count,
        'organisations': value.organisations === undefined ? undefined : (value.organisations === null ? null : (value.organisations as Array<any>).map(UserOrganisationsDtoToJSON)),
    };
}

