/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterUserDto
 */
export interface RegisterUserDto {
    /**
     * 
     * @type {string}
     * @memberof RegisterUserDto
     */
    forename: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserDto
     */
    surname: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserDto
     */
    userHandle: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserDto
     */
    mobile?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserDto
     */
    telephone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserDto
     */
    password: string;
    /**
     * 
     * @type {boolean}
     * @memberof RegisterUserDto
     */
    marketing?: boolean;
}

/**
 * Check if a given object implements the RegisterUserDto interface.
 */
export function instanceOfRegisterUserDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "forename" in value;
    isInstance = isInstance && "surname" in value;
    isInstance = isInstance && "userHandle" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function RegisterUserDtoFromJSON(json: any): RegisterUserDto {
    return RegisterUserDtoFromJSONTyped(json, false);
}

export function RegisterUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterUserDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'forename': json['forename'],
        'surname': json['surname'],
        'userHandle': json['userHandle'],
        'email': json['email'],
        'mobile': !exists(json, 'mobile') ? undefined : json['mobile'],
        'telephone': !exists(json, 'telephone') ? undefined : json['telephone'],
        'password': json['password'],
        'marketing': !exists(json, 'marketing') ? undefined : json['marketing'],
    };
}

export function RegisterUserDtoToJSON(value?: RegisterUserDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'forename': value.forename,
        'surname': value.surname,
        'userHandle': value.userHandle,
        'email': value.email,
        'mobile': value.mobile,
        'telephone': value.telephone,
        'password': value.password,
        'marketing': value.marketing,
    };
}

