/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterOrganisationResult
 */
export interface RegisterOrganisationResult {
    /**
     * 
     * @type {boolean}
     * @memberof RegisterOrganisationResult
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RegisterOrganisationResult
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisterOrganisationResult
     */
    organisationNumber?: string | null;
}

/**
 * Check if a given object implements the RegisterOrganisationResult interface.
 */
export function instanceOfRegisterOrganisationResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RegisterOrganisationResultFromJSON(json: any): RegisterOrganisationResult {
    return RegisterOrganisationResultFromJSONTyped(json, false);
}

export function RegisterOrganisationResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterOrganisationResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'organisationNumber': !exists(json, 'organisationNumber') ? undefined : json['organisationNumber'],
    };
}

export function RegisterOrganisationResultToJSON(value?: RegisterOrganisationResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'organisationNumber': value.organisationNumber,
    };
}

