/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ScheduleStatus } from './ScheduleStatus';
import {
    ScheduleStatusFromJSON,
    ScheduleStatusFromJSONTyped,
    ScheduleStatusToJSON,
} from './ScheduleStatus';
import type { TimerRequest } from './TimerRequest';
import {
    TimerRequestFromJSON,
    TimerRequestFromJSONTyped,
    TimerRequestToJSON,
} from './TimerRequest';

/**
 * 
 * @export
 * @interface ScheduleSetup
 */
export interface ScheduleSetup {
    /**
     * 
     * @type {number}
     * @memberof ScheduleSetup
     */
    slot?: number;
    /**
     * 
     * @type {ScheduleStatus}
     * @memberof ScheduleSetup
     */
    status?: ScheduleStatus;
    /**
     * 
     * @type {string}
     * @memberof ScheduleSetup
     */
    cron?: string | null;
    /**
     * 
     * @type {Array<TimerRequest>}
     * @memberof ScheduleSetup
     */
    request?: Array<TimerRequest> | null;
}

/**
 * Check if a given object implements the ScheduleSetup interface.
 */
export function instanceOfScheduleSetup(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ScheduleSetupFromJSON(json: any): ScheduleSetup {
    return ScheduleSetupFromJSONTyped(json, false);
}

export function ScheduleSetupFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleSetup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'slot': !exists(json, 'slot') ? undefined : json['slot'],
        'status': !exists(json, 'status') ? undefined : ScheduleStatusFromJSON(json['status']),
        'cron': !exists(json, 'cron') ? undefined : json['cron'],
        'request': !exists(json, 'request') ? undefined : (json['request'] === null ? null : (json['request'] as Array<any>).map(TimerRequestFromJSON)),
    };
}

export function ScheduleSetupToJSON(value?: ScheduleSetup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'slot': value.slot,
        'status': ScheduleStatusToJSON(value.status),
        'cron': value.cron,
        'request': value.request === undefined ? undefined : (value.request === null ? null : (value.request as Array<any>).map(TimerRequestToJSON)),
    };
}

