/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenSuccessResponse
 */
export interface TokenSuccessResponse {
    /**
     * 
     * @type {boolean}
     * @memberof TokenSuccessResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TokenSuccessResponse
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TokenSuccessResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TokenSuccessResponse
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TokenSuccessResponse
     */
    key?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof TokenSuccessResponse
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TokenSuccessResponse
     */
    expiry?: string | null;
}

/**
 * Check if a given object implements the TokenSuccessResponse interface.
 */
export function instanceOfTokenSuccessResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TokenSuccessResponseFromJSON(json: any): TokenSuccessResponse {
    return TokenSuccessResponseFromJSONTyped(json, false);
}

export function TokenSuccessResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenSuccessResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'key': !exists(json, 'key') ? undefined : json['key'],
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
        'expiry': !exists(json, 'expiry') ? undefined : json['expiry'],
    };
}

export function TokenSuccessResponseToJSON(value?: TokenSuccessResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'id': value.id,
        'name': value.name,
        'key': value.key,
        'enabled': value.enabled,
        'expiry': value.expiry,
    };
}

