/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UartTrigger
 */
export interface UartTrigger {
    /**
     * 
     * @type {number}
     * @memberof UartTrigger
     */
    length?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof UartTrigger
     */
    terminator?: Array<number> | null;
}

/**
 * Check if a given object implements the UartTrigger interface.
 */
export function instanceOfUartTrigger(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UartTriggerFromJSON(json: any): UartTrigger {
    return UartTriggerFromJSONTyped(json, false);
}

export function UartTriggerFromJSONTyped(json: any, ignoreDiscriminator: boolean): UartTrigger {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'length': !exists(json, 'length') ? undefined : json['length'],
        'terminator': !exists(json, 'terminator') ? undefined : json['terminator'],
    };
}

export function UartTriggerToJSON(value?: UartTrigger | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'length': value.length,
        'terminator': value.terminator,
    };
}

