/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserRole
 */
export interface UpdateUserRole {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRole
     */
    roleId?: string;
}

/**
 * Check if a given object implements the UpdateUserRole interface.
 */
export function instanceOfUpdateUserRole(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateUserRoleFromJSON(json: any): UpdateUserRole {
    return UpdateUserRoleFromJSONTyped(json, false);
}

export function UpdateUserRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserRole {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'roleId': !exists(json, 'roleId') ? undefined : json['roleId'],
    };
}

export function UpdateUserRoleToJSON(value?: UpdateUserRole | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'roleId': value.roleId,
    };
}

