/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserTokenDto
 */
export interface UserTokenDto {
    /**
     * 
     * @type {string}
     * @memberof UserTokenDto
     */
    organisationName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserTokenDto
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserTokenDto
     */
    disabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserTokenDto
     */
    tokenName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserTokenDto
     */
    tokenKey?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserTokenDto
     */
    organisationId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UserTokenDto
     */
    expiry?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof UserTokenDto
     */
    dateCreated?: Date | null;
}

/**
 * Check if a given object implements the UserTokenDto interface.
 */
export function instanceOfUserTokenDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserTokenDtoFromJSON(json: any): UserTokenDto {
    return UserTokenDtoFromJSONTyped(json, false);
}

export function UserTokenDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserTokenDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'organisationName': !exists(json, 'organisationName') ? undefined : json['organisationName'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'disabled': !exists(json, 'disabled') ? undefined : json['disabled'],
        'tokenName': !exists(json, 'tokenName') ? undefined : json['tokenName'],
        'tokenKey': !exists(json, 'tokenKey') ? undefined : json['tokenKey'],
        'organisationId': !exists(json, 'organisationId') ? undefined : json['organisationId'],
        'expiry': !exists(json, 'expiry') ? undefined : (json['expiry'] === null ? null : new Date(json['expiry'])),
        'dateCreated': !exists(json, 'dateCreated') ? undefined : (json['dateCreated'] === null ? null : new Date(json['dateCreated'])),
    };
}

export function UserTokenDtoToJSON(value?: UserTokenDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'organisationName': value.organisationName,
        'id': value.id,
        'disabled': value.disabled,
        'tokenName': value.tokenName,
        'tokenKey': value.tokenKey,
        'organisationId': value.organisationId,
        'expiry': value.expiry === undefined ? undefined : (value.expiry === null ? null : value.expiry.toISOString()),
        'dateCreated': value.dateCreated === undefined ? undefined : (value.dateCreated === null ? null : value.dateCreated.toISOString()),
    };
}

