/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserSessionsDto } from './UserSessionsDto';
import {
    UserSessionsDtoFromJSON,
    UserSessionsDtoFromJSONTyped,
    UserSessionsDtoToJSON,
} from './UserSessionsDto';

/**
 * 
 * @export
 * @interface UserSessionsResponse
 */
export interface UserSessionsResponse {
    /**
     * 
     * @type {boolean}
     * @memberof UserSessionsResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof UserSessionsResponse
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof UserSessionsResponse
     */
    count?: number;
    /**
     * 
     * @type {Array<UserSessionsDto>}
     * @memberof UserSessionsResponse
     */
    sessions?: Array<UserSessionsDto> | null;
}

/**
 * Check if a given object implements the UserSessionsResponse interface.
 */
export function instanceOfUserSessionsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserSessionsResponseFromJSON(json: any): UserSessionsResponse {
    return UserSessionsResponseFromJSONTyped(json, false);
}

export function UserSessionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSessionsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'pageNumber': !exists(json, 'pageNumber') ? undefined : json['pageNumber'],
        'count': !exists(json, 'count') ? undefined : json['count'],
        'sessions': !exists(json, 'sessions') ? undefined : (json['sessions'] === null ? null : (json['sessions'] as Array<any>).map(UserSessionsDtoFromJSON)),
    };
}

export function UserSessionsResponseToJSON(value?: UserSessionsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'pageNumber': value.pageNumber,
        'count': value.count,
        'sessions': value.sessions === undefined ? undefined : (value.sessions === null ? null : (value.sessions as Array<any>).map(UserSessionsDtoToJSON)),
    };
}

