/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserOrganisationsDto
 */
export interface UserOrganisationsDto {
    /**
     * 
     * @type {string}
     * @memberof UserOrganisationsDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserOrganisationsDto
     */
    organisationNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserOrganisationsDto
     */
    organisationName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserOrganisationsDto
     */
    roleId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserOrganisationsDto
     */
    roleName?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserOrganisationsDto
     */
    disabled?: boolean;
}

/**
 * Check if a given object implements the UserOrganisationsDto interface.
 */
export function instanceOfUserOrganisationsDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserOrganisationsDtoFromJSON(json: any): UserOrganisationsDto {
    return UserOrganisationsDtoFromJSONTyped(json, false);
}

export function UserOrganisationsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserOrganisationsDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'organisationNumber': !exists(json, 'organisationNumber') ? undefined : json['organisationNumber'],
        'organisationName': !exists(json, 'organisationName') ? undefined : json['organisationName'],
        'roleId': !exists(json, 'roleId') ? undefined : json['roleId'],
        'roleName': !exists(json, 'roleName') ? undefined : json['roleName'],
        'disabled': !exists(json, 'disabled') ? undefined : json['disabled'],
    };
}

export function UserOrganisationsDtoToJSON(value?: UserOrganisationsDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'organisationNumber': value.organisationNumber,
        'organisationName': value.organisationName,
        'roleId': value.roleId,
        'roleName': value.roleName,
        'disabled': value.disabled,
    };
}

