/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSessionsDto
 */
export interface UserSessionsDto {
    /**
     * 
     * @type {string}
     * @memberof UserSessionsDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSessionsDto
     */
    userAgent?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserSessionsDto
     */
    platform?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserSessionsDto
     */
    client?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UserSessionsDto
     */
    loginTime?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof UserSessionsDto
     */
    lastActive?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof UserSessionsDto
     */
    location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserSessionsDto
     */
    ipAddress?: string | null;
}

/**
 * Check if a given object implements the UserSessionsDto interface.
 */
export function instanceOfUserSessionsDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserSessionsDtoFromJSON(json: any): UserSessionsDto {
    return UserSessionsDtoFromJSONTyped(json, false);
}

export function UserSessionsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSessionsDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'userAgent': !exists(json, 'userAgent') ? undefined : json['userAgent'],
        'platform': !exists(json, 'platform') ? undefined : json['platform'],
        'client': !exists(json, 'client') ? undefined : json['client'],
        'loginTime': !exists(json, 'loginTime') ? undefined : (json['loginTime'] === null ? null : new Date(json['loginTime'])),
        'lastActive': !exists(json, 'lastActive') ? undefined : (json['lastActive'] === null ? null : new Date(json['lastActive'])),
        'location': !exists(json, 'location') ? undefined : json['location'],
        'ipAddress': !exists(json, 'ipAddress') ? undefined : json['ipAddress'],
    };
}

export function UserSessionsDtoToJSON(value?: UserSessionsDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'userAgent': value.userAgent,
        'platform': value.platform,
        'client': value.client,
        'loginTime': value.loginTime === undefined ? undefined : (value.loginTime === null ? null : value.loginTime.toISOString()),
        'lastActive': value.lastActive === undefined ? undefined : (value.lastActive === null ? null : value.lastActive.toISOString()),
        'location': value.location,
        'ipAddress': value.ipAddress,
    };
}

