/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserTokenDto } from './UserTokenDto';
import {
    UserTokenDtoFromJSON,
    UserTokenDtoFromJSONTyped,
    UserTokenDtoToJSON,
} from './UserTokenDto';

/**
 * 
 * @export
 * @interface UserTokenResponse
 */
export interface UserTokenResponse {
    /**
     * 
     * @type {boolean}
     * @memberof UserTokenResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof UserTokenResponse
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof UserTokenResponse
     */
    count?: number;
    /**
     * 
     * @type {Array<UserTokenDto>}
     * @memberof UserTokenResponse
     */
    tokens?: Array<UserTokenDto> | null;
}

/**
 * Check if a given object implements the UserTokenResponse interface.
 */
export function instanceOfUserTokenResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserTokenResponseFromJSON(json: any): UserTokenResponse {
    return UserTokenResponseFromJSONTyped(json, false);
}

export function UserTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserTokenResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'pageNumber': !exists(json, 'pageNumber') ? undefined : json['pageNumber'],
        'count': !exists(json, 'count') ? undefined : json['count'],
        'tokens': !exists(json, 'tokens') ? undefined : (json['tokens'] === null ? null : (json['tokens'] as Array<any>).map(UserTokenDtoFromJSON)),
    };
}

export function UserTokenResponseToJSON(value?: UserTokenResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'pageNumber': value.pageNumber,
        'count': value.count,
        'tokens': value.tokens === undefined ? undefined : (value.tokens === null ? null : (value.tokens as Array<any>).map(UserTokenDtoToJSON)),
    };
}

