/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AzureMessage } from './AzureMessage';
import {
    AzureMessageFromJSON,
    AzureMessageFromJSONTyped,
    AzureMessageToJSON,
} from './AzureMessage';
import type { GatewayClaim } from './GatewayClaim';
import {
    GatewayClaimFromJSON,
    GatewayClaimFromJSONTyped,
    GatewayClaimToJSON,
} from './GatewayClaim';
import type { GatewayGpio } from './GatewayGpio';
import {
    GatewayGpioFromJSON,
    GatewayGpioFromJSONTyped,
    GatewayGpioToJSON,
} from './GatewayGpio';
import type { GatewayMqtt } from './GatewayMqtt';
import {
    GatewayMqttFromJSON,
    GatewayMqttFromJSONTyped,
    GatewayMqttToJSON,
} from './GatewayMqtt';
import type { GatewayNetwork } from './GatewayNetwork';
import {
    GatewayNetworkFromJSON,
    GatewayNetworkFromJSONTyped,
    GatewayNetworkToJSON,
} from './GatewayNetwork';
import type { GatewayNode } from './GatewayNode';
import {
    GatewayNodeFromJSON,
    GatewayNodeFromJSONTyped,
    GatewayNodeToJSON,
} from './GatewayNode';
import type { GatewaySchedule } from './GatewaySchedule';
import {
    GatewayScheduleFromJSON,
    GatewayScheduleFromJSONTyped,
    GatewayScheduleToJSON,
} from './GatewaySchedule';
import type { GatewayTimer } from './GatewayTimer';
import {
    GatewayTimerFromJSON,
    GatewayTimerFromJSONTyped,
    GatewayTimerToJSON,
} from './GatewayTimer';
import type { GatewayWifi } from './GatewayWifi';
import {
    GatewayWifiFromJSON,
    GatewayWifiFromJSONTyped,
    GatewayWifiToJSON,
} from './GatewayWifi';
import type { VyneDevice } from './VyneDevice';
import {
    VyneDeviceFromJSON,
    VyneDeviceFromJSONTyped,
    VyneDeviceToJSON,
} from './VyneDevice';

/**
 * 
 * @export
 * @interface VyneGateway
 */
export interface VyneGateway {
    /**
     * 
     * @type {string}
     * @memberof VyneGateway
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VyneGateway
     */
    partNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VyneGateway
     */
    systemOs?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VyneGateway
     */
    systemVersion?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof VyneGateway
     */
    lastUpdated?: Date | null;
    /**
     * 
     * @type {AzureMessage}
     * @memberof VyneGateway
     */
    lastMessage?: AzureMessage;
    /**
     * 
     * @type {GatewayClaim}
     * @memberof VyneGateway
     */
    claim?: GatewayClaim;
    /**
     * 
     * @type {GatewayGpio}
     * @memberof VyneGateway
     */
    gpio?: GatewayGpio;
    /**
     * 
     * @type {GatewayTimer}
     * @memberof VyneGateway
     */
    timer?: GatewayTimer;
    /**
     * 
     * @type {GatewayWifi}
     * @memberof VyneGateway
     */
    wifi?: GatewayWifi;
    /**
     * 
     * @type {GatewayMqtt}
     * @memberof VyneGateway
     */
    mqtt?: GatewayMqtt;
    /**
     * 
     * @type {GatewayNetwork}
     * @memberof VyneGateway
     */
    network?: GatewayNetwork;
    /**
     * 
     * @type {GatewaySchedule}
     * @memberof VyneGateway
     */
    schedule?: GatewaySchedule;
    /**
     * 
     * @type {VyneDevice}
     * @memberof VyneGateway
     */
    device?: VyneDevice;
    /**
     * 
     * @type {GatewayNode}
     * @memberof VyneGateway
     */
    node?: GatewayNode;
}

/**
 * Check if a given object implements the VyneGateway interface.
 */
export function instanceOfVyneGateway(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VyneGatewayFromJSON(json: any): VyneGateway {
    return VyneGatewayFromJSONTyped(json, false);
}

export function VyneGatewayFromJSONTyped(json: any, ignoreDiscriminator: boolean): VyneGateway {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'partNumber': !exists(json, 'partNumber') ? undefined : json['partNumber'],
        'systemOs': !exists(json, 'systemOs') ? undefined : json['systemOs'],
        'systemVersion': !exists(json, 'systemVersion') ? undefined : json['systemVersion'],
        'lastUpdated': !exists(json, 'lastUpdated') ? undefined : (json['lastUpdated'] === null ? null : new Date(json['lastUpdated'])),
        'lastMessage': !exists(json, 'lastMessage') ? undefined : AzureMessageFromJSON(json['lastMessage']),
        'claim': !exists(json, 'claim') ? undefined : GatewayClaimFromJSON(json['claim']),
        'gpio': !exists(json, 'gpio') ? undefined : GatewayGpioFromJSON(json['gpio']),
        'timer': !exists(json, 'timer') ? undefined : GatewayTimerFromJSON(json['timer']),
        'wifi': !exists(json, 'wifi') ? undefined : GatewayWifiFromJSON(json['wifi']),
        'mqtt': !exists(json, 'mqtt') ? undefined : GatewayMqttFromJSON(json['mqtt']),
        'network': !exists(json, 'network') ? undefined : GatewayNetworkFromJSON(json['network']),
        'schedule': !exists(json, 'schedule') ? undefined : GatewayScheduleFromJSON(json['schedule']),
        'device': !exists(json, 'device') ? undefined : VyneDeviceFromJSON(json['device']),
        'node': !exists(json, 'node') ? undefined : GatewayNodeFromJSON(json['node']),
    };
}

export function VyneGatewayToJSON(value?: VyneGateway | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'partNumber': value.partNumber,
        'systemOs': value.systemOs,
        'systemVersion': value.systemVersion,
        'lastUpdated': value.lastUpdated === undefined ? undefined : (value.lastUpdated === null ? null : value.lastUpdated.toISOString()),
        'lastMessage': AzureMessageToJSON(value.lastMessage),
        'claim': GatewayClaimToJSON(value.claim),
        'gpio': GatewayGpioToJSON(value.gpio),
        'timer': GatewayTimerToJSON(value.timer),
        'wifi': GatewayWifiToJSON(value.wifi),
        'mqtt': GatewayMqttToJSON(value.mqtt),
        'network': GatewayNetworkToJSON(value.network),
        'schedule': GatewayScheduleToJSON(value.schedule),
        'device': VyneDeviceToJSON(value.device),
        'node': GatewayNodeToJSON(value.node),
    };
}

