/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DevicePower } from './DevicePower';
import {
    DevicePowerFromJSON,
    DevicePowerFromJSONTyped,
    DevicePowerToJSON,
} from './DevicePower';
import type { DeviceVersion } from './DeviceVersion';
import {
    DeviceVersionFromJSON,
    DeviceVersionFromJSONTyped,
    DeviceVersionToJSON,
} from './DeviceVersion';
import type { NodeAddress } from './NodeAddress';
import {
    NodeAddressFromJSON,
    NodeAddressFromJSONTyped,
    NodeAddressToJSON,
} from './NodeAddress';
import type { NodeData } from './NodeData';
import {
    NodeDataFromJSON,
    NodeDataFromJSONTyped,
    NodeDataToJSON,
} from './NodeData';
import type { NodeLocation } from './NodeLocation';
import {
    NodeLocationFromJSON,
    NodeLocationFromJSONTyped,
    NodeLocationToJSON,
} from './NodeLocation';

/**
 * 
 * @export
 * @interface VyneNode
 */
export interface VyneNode {
    /**
     * 
     * @type {string}
     * @memberof VyneNode
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VyneNode
     */
    partNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VyneNode
     */
    gatewayId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof VyneNode
     */
    firstSeen?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof VyneNode
     */
    lastUpdated?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof VyneNode
     */
    enable?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof VyneNode
     */
    name?: string | null;
    /**
     * 
     * @type {NodeLocation}
     * @memberof VyneNode
     */
    location?: NodeLocation;
    /**
     * 
     * @type {DeviceVersion}
     * @memberof VyneNode
     */
    version?: DeviceVersion;
    /**
     * 
     * @type {number}
     * @memberof VyneNode
     */
    setup?: number;
    /**
     * 
     * @type {NodeAddress}
     * @memberof VyneNode
     */
    address?: NodeAddress;
    /**
     * 
     * @type {NodeData}
     * @memberof VyneNode
     */
    data?: NodeData;
    /**
     * 
     * @type {DevicePower}
     * @memberof VyneNode
     */
    power?: DevicePower;
    /**
     * 
     * @type {boolean}
     * @memberof VyneNode
     */
    identify?: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof VyneNode
     */
    pin?: Array<number> | null;
}

/**
 * Check if a given object implements the VyneNode interface.
 */
export function instanceOfVyneNode(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VyneNodeFromJSON(json: any): VyneNode {
    return VyneNodeFromJSONTyped(json, false);
}

export function VyneNodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VyneNode {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'partNumber': !exists(json, 'partNumber') ? undefined : json['partNumber'],
        'gatewayId': !exists(json, 'gatewayId') ? undefined : json['gatewayId'],
        'firstSeen': !exists(json, 'firstSeen') ? undefined : (json['firstSeen'] === null ? null : new Date(json['firstSeen'])),
        'lastUpdated': !exists(json, 'lastUpdated') ? undefined : (json['lastUpdated'] === null ? null : new Date(json['lastUpdated'])),
        'enable': !exists(json, 'enable') ? undefined : json['enable'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'location': !exists(json, 'location') ? undefined : NodeLocationFromJSON(json['location']),
        'version': !exists(json, 'version') ? undefined : DeviceVersionFromJSON(json['version']),
        'setup': !exists(json, 'setup') ? undefined : json['setup'],
        'address': !exists(json, 'address') ? undefined : NodeAddressFromJSON(json['address']),
        'data': !exists(json, 'data') ? undefined : NodeDataFromJSON(json['data']),
        'power': !exists(json, 'power') ? undefined : DevicePowerFromJSON(json['power']),
        'identify': !exists(json, 'identify') ? undefined : json['identify'],
        'pin': !exists(json, 'pin') ? undefined : json['pin'],
    };
}

export function VyneNodeToJSON(value?: VyneNode | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'partNumber': value.partNumber,
        'gatewayId': value.gatewayId,
        'firstSeen': value.firstSeen === undefined ? undefined : (value.firstSeen === null ? null : value.firstSeen.toISOString()),
        'lastUpdated': value.lastUpdated === undefined ? undefined : (value.lastUpdated === null ? null : value.lastUpdated.toISOString()),
        'enable': value.enable,
        'name': value.name,
        'location': NodeLocationToJSON(value.location),
        'version': DeviceVersionToJSON(value.version),
        'setup': value.setup,
        'address': NodeAddressToJSON(value.address),
        'data': NodeDataToJSON(value.data),
        'power': DevicePowerToJSON(value.power),
        'identify': value.identify,
        'pin': value.pin,
    };
}

