/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DeviceCloud } from './DeviceCloud';
import {
    DeviceCloudFromJSON,
    DeviceCloudFromJSONTyped,
    DeviceCloudToJSON,
} from './DeviceCloud';
import type { DeviceLocation } from './DeviceLocation';
import {
    DeviceLocationFromJSON,
    DeviceLocationFromJSONTyped,
    DeviceLocationToJSON,
} from './DeviceLocation';
import type { DevicePower } from './DevicePower';
import {
    DevicePowerFromJSON,
    DevicePowerFromJSONTyped,
    DevicePowerToJSON,
} from './DevicePower';
import type { DeviceSession } from './DeviceSession';
import {
    DeviceSessionFromJSON,
    DeviceSessionFromJSONTyped,
    DeviceSessionToJSON,
} from './DeviceSession';
import type { DeviceSupport } from './DeviceSupport';
import {
    DeviceSupportFromJSON,
    DeviceSupportFromJSONTyped,
    DeviceSupportToJSON,
} from './DeviceSupport';
import type { DeviceUptime } from './DeviceUptime';
import {
    DeviceUptimeFromJSON,
    DeviceUptimeFromJSONTyped,
    DeviceUptimeToJSON,
} from './DeviceUptime';
import type { DeviceVersion } from './DeviceVersion';
import {
    DeviceVersionFromJSON,
    DeviceVersionFromJSONTyped,
    DeviceVersionToJSON,
} from './DeviceVersion';

/**
 * 
 * @export
 * @interface VyneDevice
 */
export interface VyneDevice {
    /**
     * 
     * @type {string}
     * @memberof VyneDevice
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VyneDevice
     */
    key?: string | null;
    /**
     * 
     * @type {DeviceSupport}
     * @memberof VyneDevice
     */
    support?: DeviceSupport;
    /**
     * 
     * @type {DeviceCloud}
     * @memberof VyneDevice
     */
    cloud?: DeviceCloud;
    /**
     * 
     * @type {DeviceUptime}
     * @memberof VyneDevice
     */
    uptime?: DeviceUptime;
    /**
     * 
     * @type {boolean}
     * @memberof VyneDevice
     */
    activity?: boolean;
    /**
     * 
     * @type {number}
     * @memberof VyneDevice
     */
    temperature?: number;
    /**
     * 
     * @type {number}
     * @memberof VyneDevice
     */
    brightness?: number;
    /**
     * 
     * @type {DevicePower}
     * @memberof VyneDevice
     */
    power?: DevicePower;
    /**
     * 
     * @type {DeviceSession}
     * @memberof VyneDevice
     */
    session?: DeviceSession;
    /**
     * 
     * @type {DeviceVersion}
     * @memberof VyneDevice
     */
    version?: DeviceVersion;
    /**
     * 
     * @type {DeviceLocation}
     * @memberof VyneDevice
     */
    location?: DeviceLocation;
}

/**
 * Check if a given object implements the VyneDevice interface.
 */
export function instanceOfVyneDevice(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VyneDeviceFromJSON(json: any): VyneDevice {
    return VyneDeviceFromJSONTyped(json, false);
}

export function VyneDeviceFromJSONTyped(json: any, ignoreDiscriminator: boolean): VyneDevice {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'key': !exists(json, 'key') ? undefined : json['key'],
        'support': !exists(json, 'support') ? undefined : DeviceSupportFromJSON(json['support']),
        'cloud': !exists(json, 'cloud') ? undefined : DeviceCloudFromJSON(json['cloud']),
        'uptime': !exists(json, 'uptime') ? undefined : DeviceUptimeFromJSON(json['uptime']),
        'activity': !exists(json, 'activity') ? undefined : json['activity'],
        'temperature': !exists(json, 'temperature') ? undefined : json['temperature'],
        'brightness': !exists(json, 'brightness') ? undefined : json['brightness'],
        'power': !exists(json, 'power') ? undefined : DevicePowerFromJSON(json['power']),
        'session': !exists(json, 'session') ? undefined : DeviceSessionFromJSON(json['session']),
        'version': !exists(json, 'version') ? undefined : DeviceVersionFromJSON(json['version']),
        'location': !exists(json, 'location') ? undefined : DeviceLocationFromJSON(json['location']),
    };
}

export function VyneDeviceToJSON(value?: VyneDevice | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'key': value.key,
        'support': DeviceSupportToJSON(value.support),
        'cloud': DeviceCloudToJSON(value.cloud),
        'uptime': DeviceUptimeToJSON(value.uptime),
        'activity': value.activity,
        'temperature': value.temperature,
        'brightness': value.brightness,
        'power': DevicePowerToJSON(value.power),
        'session': DeviceSessionToJSON(value.session),
        'version': DeviceVersionToJSON(value.version),
        'location': DeviceLocationToJSON(value.location),
    };
}

