/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const WebhookStatus = {
    Queued: 0,
    Pending: 1,
    Failed: 2,
    Success: 3
} as const;
export type WebhookStatus = typeof WebhookStatus[keyof typeof WebhookStatus];


export function WebhookStatusFromJSON(json: any): WebhookStatus {
    return WebhookStatusFromJSONTyped(json, false);
}

export function WebhookStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookStatus {
    return json as WebhookStatus;
}

export function WebhookStatusToJSON(value?: WebhookStatus | null): any {
    return value as any;
}

