/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { WebhookRetry } from './WebhookRetry';
import {
    WebhookRetryFromJSON,
    WebhookRetryFromJSONTyped,
    WebhookRetryToJSON,
} from './WebhookRetry';

/**
 * 
 * @export
 * @interface WebhookRetryRequest
 */
export interface WebhookRetryRequest {
    /**
     * 
     * @type {Array<WebhookRetry>}
     * @memberof WebhookRetryRequest
     */
    retries: Array<WebhookRetry>;
}

/**
 * Check if a given object implements the WebhookRetryRequest interface.
 */
export function instanceOfWebhookRetryRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "retries" in value;

    return isInstance;
}

export function WebhookRetryRequestFromJSON(json: any): WebhookRetryRequest {
    return WebhookRetryRequestFromJSONTyped(json, false);
}

export function WebhookRetryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookRetryRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'retries': ((json['retries'] as Array<any>).map(WebhookRetryFromJSON)),
    };
}

export function WebhookRetryRequestToJSON(value?: WebhookRetryRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'retries': ((value.retries as Array<any>).map(WebhookRetryToJSON)),
    };
}

