/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookHeaders
 */
export interface WebhookHeaders {
    /**
     * 
     * @type {string}
     * @memberof WebhookHeaders
     */
    key?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WebhookHeaders
     */
    value?: string | null;
}

/**
 * Check if a given object implements the WebhookHeaders interface.
 */
export function instanceOfWebhookHeaders(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WebhookHeadersFromJSON(json: any): WebhookHeaders {
    return WebhookHeadersFromJSONTyped(json, false);
}

export function WebhookHeadersFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookHeaders {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': !exists(json, 'key') ? undefined : json['key'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function WebhookHeadersToJSON(value?: WebhookHeaders | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'value': value.value,
    };
}

