/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CallLogDto } from './CallLogDto';
import {
    CallLogDtoFromJSON,
    CallLogDtoFromJSONTyped,
    CallLogDtoToJSON,
} from './CallLogDto';

/**
 * 
 * @export
 * @interface WebhookLogsResponse
 */
export interface WebhookLogsResponse {
    /**
     * 
     * @type {boolean}
     * @memberof WebhookLogsResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof WebhookLogsResponse
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof WebhookLogsResponse
     */
    count?: number;
    /**
     * 
     * @type {Array<CallLogDto>}
     * @memberof WebhookLogsResponse
     */
    calls?: Array<CallLogDto> | null;
}

/**
 * Check if a given object implements the WebhookLogsResponse interface.
 */
export function instanceOfWebhookLogsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WebhookLogsResponseFromJSON(json: any): WebhookLogsResponse {
    return WebhookLogsResponseFromJSONTyped(json, false);
}

export function WebhookLogsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookLogsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'pageNumber': !exists(json, 'pageNumber') ? undefined : json['pageNumber'],
        'count': !exists(json, 'count') ? undefined : json['count'],
        'calls': !exists(json, 'calls') ? undefined : (json['calls'] === null ? null : (json['calls'] as Array<any>).map(CallLogDtoFromJSON)),
    };
}

export function WebhookLogsResponseToJSON(value?: WebhookLogsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'pageNumber': value.pageNumber,
        'count': value.count,
        'calls': value.calls === undefined ? undefined : (value.calls === null ? null : (value.calls as Array<any>).map(CallLogDtoToJSON)),
    };
}

