/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { WifiSlot } from './WifiSlot';
import {
    WifiSlotFromJSON,
    WifiSlotFromJSONTyped,
    WifiSlotToJSON,
} from './WifiSlot';

/**
 * 
 * @export
 * @interface WifiStatus
 */
export interface WifiStatus {
    /**
     * 
     * @type {WifiSlot}
     * @memberof WifiStatus
     */
    slot?: WifiSlot;
    /**
     * 
     * @type {number}
     * @memberof WifiStatus
     */
    signal?: number;
}

/**
 * Check if a given object implements the WifiStatus interface.
 */
export function instanceOfWifiStatus(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WifiStatusFromJSON(json: any): WifiStatus {
    return WifiStatusFromJSONTyped(json, false);
}

export function WifiStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): WifiStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'slot': !exists(json, 'slot') ? undefined : WifiSlotFromJSON(json['slot']),
        'signal': !exists(json, 'signal') ? undefined : json['signal'],
    };
}

export function WifiStatusToJSON(value?: WifiStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'slot': WifiSlotToJSON(value.slot),
        'signal': value.signal,
    };
}

