/* tslint:disable */
/* eslint-disable */
/**
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const WifiSlot = {
    Primary: 0,
    Secondary: 1
} as const;
export type WifiSlot = typeof WifiSlot[keyof typeof WifiSlot];


export function WifiSlotFromJSON(json: any): WifiSlot {
    return WifiSlotFromJSONTyped(json, false);
}

export function WifiSlotFromJSONTyped(json: any, ignoreDiscriminator: boolean): WifiSlot {
    return json as WifiSlot;
}

export function WifiSlotToJSON(value?: WifiSlot | null): any {
    return value as any;
}

